export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  USER_NOT_FOUND: 'USER_NOT_FOUND',

  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_SLUG_TAKEN: 'ORG_SLUG_TAKEN',
  ORG_FORBIDDEN: 'ORG_FORBIDDEN',
  ORG_MEMBER_EXISTS: 'ORG_MEMBER_EXISTS',

  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
  CHANNEL_FORBIDDEN: 'CHANNEL_FORBIDDEN',
  CHANNEL_MEMBER_EXISTS: 'CHANNEL_MEMBER_EXISTS',

  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_FORBIDDEN: 'MESSAGE_FORBIDDEN',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
